version: "3.9"
services:
  psql:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=olim123
      - POSTGRES_DB=olimbank
    container_name: postgresdb
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: olimbank:latest
    # image: alimkhan7007/bank_k8s_image:0.0.1 # for k8s
    container_name: bank_api
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:olim123@postgresdb:5432/olimbank?sslmode=disable
    depends_on:
      - psql
    entrypoint: ["/app/wait-for.sh", "postgresdb:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
