version: "3.9"
services:
  psql:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=olim123
      - POSTGRES_DB=olimbank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    container_name: postgresdb
  redis: 
    image: redis:7-alpine
    container_name: redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: olimbank:latest
    # image: alimkhan7007/bank_k8s_image:0.0.1 # for k8s
    container_name: bank_api
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:olim123@postgresdb:5432/olimbank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - psql
      - redis
    entrypoint: ["/app/wait-for.sh", "postgresdb:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume: